name: Update Donation Data
on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-donations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run donation collector
        run: python github_collector.py
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add donations.json total_raised.json
          git diff --staged --quiet || git commit -m "Auto-update donations: $(date '+%Y-%m-%d %H:%M:%S UTC')"
          git push
